SETTINGS_PATH         = Pathname.new File.join(MAIN_PATH, 'settings')
RESOURCES_PATH        = Pathname.new File.join(MAIN_PATH, 'resources')
GAME_LIB_PATH         = Pathname.new File.join(MAIN_PATH, 'game_lib')
LOADERS_PATH          = Pathname.new File.join(MAIN_PATH, 'loaders')
WINDOW_STATES_PATH    = Pathname.new File.join(MAIN_PATH, 'window_states')
GAME_SESSION_PATH     = Pathname.new File.join(WINDOW_STATES_PATH, 'game_session')
MAIN_MENU_PATH        = Pathname.new File.join(WINDOW_STATES_PATH, 'main_menu')
STAGE_RESOURCE_PATH   = Pathname.new File.join(RESOURCES_PATH, 'stages')
SPRITE_RESOURCE_PATH  = Pathname.new File.join(RESOURCES_PATH, 'sprites')

